# Generated by Django 4.0.3 on 2022-03-19 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='addressee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='message_addressee', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='message',
            name='cat',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='Support.categorymessage', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Support.statusmessage', verbose_name='Message status'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
