# Generated by Django 4.0.3 on 2022-03-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_support',
            field=models.BooleanField(default=False, verbose_name='Поддержка ли он'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
